import Config

# Configure your database.
# Connection settings can be overridden via env vars so the same config works
# for a local Postgres ("localhost") and the Docker Compose service ("db").
config :seovivu, Seovivu.Repo,
  username: System.get_env("DATABASE_USER", "postgres"),
  password: System.get_env("DATABASE_PASSWORD", "postgres"),
  hostname: System.get_env("DATABASE_HOST", "localhost"),
  database: System.get_env("DATABASE_NAME", "seovivu_dev"),
  port: String.to_integer(System.get_env("DATABASE_PORT", "5432")),
  stacktrace: true,
  show_sensitive_data_on_connection_error: true,
  pool_size: 10

# For development, we disable any cache and enable
# debugging and code reloading.
#
# The watchers configuration can be used to run external
# watchers to your application. For example, we can use it
# to bundle .js and .css sources.
config :seovivu, SeovivuWeb.Endpoint,
  # Binding to loopback ipv4 address prevents access from other machines.
  # Inside Docker we must bind to all interfaces so the port is reachable from
  # the host; set BIND_ALL_INTERFACES=true (done in docker-compose.yml).
  http: [
    ip:
      if(System.get_env("BIND_ALL_INTERFACES") in ~w(true 1),
        do: {0, 0, 0, 0},
        else: {127, 0, 0, 1}
      )
  ],
  check_origin: false,
  code_reloader: true,
  debug_errors: true,
  secret_key_base: "/OPfS90/t2/CdDxKAuGVefMianu//tI71KsuU7MBgEjEVIN/Xb+hXxhqI/rlXz0z",
  watchers: [
    esbuild: {Esbuild, :install_and_run, [:seovivu, ~w(--sourcemap=inline --watch)]},
    tailwind: {Tailwind, :install_and_run, [:seovivu, ~w(--watch)]}
  ]

# ## SSL Support
#
# In order to use HTTPS in development, a self-signed
# certificate can be generated by running the following
# Mix task:
#
#     mix phx.gen.cert
#
# Run `mix help phx.gen.cert` for more information.
#
# The `http:` config above can be replaced with:
#
#     https: [
#       port: 4001,
#       cipher_suite: :strong,
#       keyfile: "priv/cert/selfsigned_key.pem",
#       certfile: "priv/cert/selfsigned.pem"
#     ],
#
# If desired, both `http:` and `https:` keys can be
# configured to run both http and https servers on
# different ports.

# Reload browser tabs when matching files change.
config :seovivu, SeovivuWeb.Endpoint,
  live_reload: [
    web_console_logger: true,
    patterns: [
      # Static assets, except user uploads
      ~r"priv/static/(?!uploads/).*\.(js|css|png|jpeg|jpg|gif|svg)$"E,
      # Gettext translations
      ~r"priv/gettext/.*\.po$"E,
      # Router, Controllers, LiveViews and LiveComponents
      ~r"lib/seovivu_web/router\.ex$"E,
      ~r"lib/seovivu_web/(controllers|live|components)/.*\.(ex|heex)$"E
    ]
  ]

# Enable dev routes for dashboard and mailbox
config :seovivu, dev_routes: true

# Receive Telegram updates via long-polling in development (no public webhook).
config :seovivu, :telegram_poller, true

# Do not include metadata nor timestamps in development logs
config :logger, :default_formatter, format: "[$level] $message\n"

# Set a higher stacktrace during development. Avoid configuring such
# in production as building large stacktraces may be expensive.
config :phoenix, :stacktrace_depth, 20

# Initialize plugs at runtime for faster development compilation
config :phoenix, :plug_init_mode, :runtime

config :phoenix_live_view,
  # Include debug annotations and locations in rendered markup.
  # Changing this configuration will require mix clean and a full recompile.
  debug_heex_annotations: true,
  debug_attributes: true,
  # Enable helpful, but potentially expensive runtime checks
  enable_expensive_runtime_checks: true

# Disable swoosh api client as it is only required for production adapters.
config :swoosh, :api_client, false
